pipeline {
    agent { label 'agent-staging' }
    

    stages {    
        /*stage('Ignore-SSL') {
         *    steps {
         *       sh 'git config --global http.sslVerify false'
         *   }
         *}
         */
        
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/staging']],
                    userRemoteConfigs: [[
                        url: 'https://54.85.160.177/devops/weather.git',
                        credentialsId: 'gitlab-impersonation-token'
                    ]]
                ])
                
                script {
                    env.BRANCH_NAME = 'staging'
                }
            }
        }

        stage('Pylint'){
            steps{
                script {
                    def output = sh(
                        script: '''
                            . /home/ubuntu/venv/bin/activate
                            pylint main.py --score=y | tail -2 | awk '{print $7; exit}' | awk -F '/' '{print $1}'

                        ''',
                        returnStdout: true
                    ).trim()


                    float score = 0.0
                    try {
                        score = output.toFloat()
                    } catch (Exception e) {
                        error("Failed to parse pylint score: ${output}")
                    }

                    if (score < 6.0) {
                        error("Pylint score too low: ${score}")
                    }

                    env.PYLINT_SCORE = score
                }
            }
        }

        stage('Unpack App and Test Reachable'){
            steps{
                sh '''
                sudo docker build -t weather_app -f Dockerfile .
                sudo docker compose up -d
                '''
                sleep(10)

                sh '''
                    curl --silent --fail http://172.31.16.153
                '''

                sh '''sudo docker compose down'''
            }
        }
        
        stage('Upload Working Image to DockerHub'){
            steps {
                withCredentials([usernamePassword(
                credentialsId: 'dockerhub-credentials',
                usernameVariable: 'DOCKER_USER',
                passwordVariable: 'DOCKER_PASS'
                )])
                {
                    sh '''echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'''
                    sh '''docker info | grep Username'''
                    sh '''docker tag weather_app:latest ayashben/weather_app:latest'''
                    sh '''docker push ayashben/weather_app:latest'''
                }
            }
        }

        stage('Deploy App to Production'){
            steps {
                echo "This stage is reserved for later use"
            }
        }

        stage('Teardown'){
            steps {
                echo "This stage is reserved for later use"
            }
        }
    }
    post {
        always {
            cleanWs()
            sh '''
                docker ps -aq | xargs -r docker stop
                docker ps -aq | xargs -r docker rm
                '''
        }
        success {
            slackSend(channel: "#devops-alert-succeeded", message: """
            *Build Success*
            *Job:* ${env.JOB_NAME}
            *Build:* #${env.BUILD_NUMBER}
            *Branch:* ${env.BRANCH_NAME}
            *Commit:* ${env.GIT_COMMIT}
            *Stage:* ${env.STAGE_NAME}
            *Pylint Score:* ${env.PYLINT_SCORE}
            *URL:* ${env.BUILD_URL}
            """)
            build job: 'deploy_production', wait: false
        }
        failure {
            slackSend(channel: "#devops-alert-failed", message: """
            *Build Failed*
            *Job:* ${env.JOB_NAME}
            *Build:* #${env.BUILD_NUMBER}
            *Branch:* ${env.BRANCH_NAME}
            *Commit:* ${env.GIT_COMMIT}
            *Stage:* ${env.STAGE_NAME}
            *Pylint Score:* ${env.PYLINT_SCORE}
            *URL:* ${env.BUILD_URL}
            """)
        }
    }
}